---
title: "Add-ons Survey"
author: "Ben Miroglio"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: cosmo
    toc_float: true
params:
  who_purchased:
    label: "Did your employer purchase the computer you are using to complete this survey?"
    value: All
    input: select
    choices: [All, "I'm not sure", "No", "Yes"]
---

```{r, include=F}
library(data.table, quietly = T)
library(ggplot2, quietly = T)


```

```{R, include=F, cache=T}
d <- fread("~/Desktop/addonsSurveyExport.csv")
N <- nrow(d)
```

We had `r N` users complete this survey.

# Survey Response Summaries

---

```{r, include=F}
q = "Did your employer purchase the computer you are using to complete this survey?"
```

### `r q`

```{R, fig.height=5, fig.width=8, echo=F}
ggplot(d, aes(d[,get(q)])) +
  geom_bar(aes(y = (..count..)/sum(..count..)), fill='#feb475') + 
  theme_bw() + 
  theme(axis.text.x = element_text(size=14)) + labs(y='% Responses', x='')

```

---

```{R, include=F}
q = "How recently was Firefox installed on the computer you are using to complete this survey?"
```

### `r q`

```{R, fig.height=5, fig.width=8, echo=F}
ggplot(d, aes(d[,get(q)])) +
  geom_bar(aes(y = (..count..)/sum(..count..)), fill='#feb475') + 
  theme_bw() + 
  theme(axis.text.x = element_text(size=14, angle = 35, vjust=1, hjust = 1)) + labs(y='% Responses', x='')

```

---

```{R, include=F}
q = "Have you added any add-ons or extensions to Firefox on the computer you are using to complete this survey?"
```

### `r q`

```{R, fig.height=5, fig.width=8, echo=F}
ggplot(d, aes(d[,get(q)])) +
  geom_bar(aes(y = (..count..)/sum(..count..)), fill='#feb475') + 
  theme_bw() + 
  theme(axis.text.x = element_text(size=14)) + labs(y='% Responses', x='')

```

---

```{R, include=F}
q = "Why was Firefox installed on the computer you are using to complete this survey?"
```

### `r q`

```{R, fig.height=5, fig.width=12, echo=F}
ggplot(d[get(q) != ''], aes(get(q)))  +
  geom_bar(aes(y = (..count..)/sum(..count..)), fill='#feb475') + 
  theme_bw() + coord_flip() +
  theme(axis.text.y = element_text(size=14)) + labs(y='% Responses', x='')

```

---

```{R, include=F}
q = "Have you added any add-ons or extensions to Firefox on the computer you are using to complete this survey?"
```

### `r q`

```{R, fig.height=5, fig.width=8, echo=F}
ggplot(d[get(q) != ''], aes(get(q)))  +
  geom_bar(aes(y = (..count..)/sum(..count..)), fill='#feb475') + 
  theme_bw() +
  theme(axis.text.x = element_text(size=14)) + labs(y='% Responses', x='')

```

---

```{R, include=F}
q = "How soon after installing Firefox did you install the first add-on / extension?"
```

### `r q`

```{R, fig.height=5, fig.width=12, echo=F}
ggplot(d[get(q) != ''], aes(get(q)))  +
  geom_bar(aes(y = (..count..)/sum(..count..)), fill='#feb475') + 
  theme_bw() + coord_flip() +
  theme(axis.text.y = element_text(size=14)) + labs(y='% Responses', x='')

```


---

```{R, include=F}
q = "Have you used the add-ons / extensions you installed before?"
```

### `r q`

```{R, fig.height=5, fig.width=12, echo=F}
ggplot(d[get(q) != ''], aes(get(q)))  +
  geom_bar(aes(y = (..count..)/sum(..count..)), fill='#feb475') + 
  theme_bw() + coord_flip() +
  theme(axis.text.y = element_text(size=14)) + labs(y='% Responses', x='')

```

---

### "How did you discover the add-ons / extensions you installed?"

```{R, fig.height=5, fig.width=12, echo=F}

addon_disco <- data.table()

for (i in colnames(d)[which(grepl("How did you discover the add-ons / extensions you installed?", colnames(d)))]) {
  di <- d[get(i) != ''][,get(i)]
  addon_disco <- unique(rbind(addon_disco, data.table(resp=strsplit(i, ':')[[1]][1], count=length(di))))
}

addon_disco$pct <- addon_disco$count / sum(addon_disco$count) * 100


ggplot(addon_disco, aes(x=resp, y=pct)) +
  geom_col(fill='#feb475') + 
  theme_bw() + coord_flip() +
  theme(axis.text.y = element_text(size=14)) + labs(y='% Responses', x='')
```





